name: Comment on Pull Request

on:
  pull_request:
    types: [opened,synchronize]

jobs:
  comment-job:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        cur; -X POST -H "authorization: token $GITHUB_TOKEN"\
        -d "{body": "Thank you for your contribution!"}' \
        https://api.github.com/repos/OWNER/REPO/issues/$PR_NUMBER/comments
