name: Example workflow

on:
  workflow_dispatch: 
  

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
    -  name: Checkout repository
       uses: actions/checkout@v2

    - name: Make changes
      
      run: |
        git config --global user.email "samanvitakappara@gmail.com"
        git config --global user.name"samanvitakappara"
       
        echo "new changes" >> changes.txt
        git add changes.txt
        git commit -m "add changes"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git push origin feature
      
        
      
        
