name: Checkout another repository

on:
  pull_request:
    types: [opened,synchronize]

jobs:
  comment-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout another repository
      uses: actions/checkout@v2

    - name: Checkout another repository
      uses: actions/checkout@v2
      with: 
        repository: samanvitakappara/training2
        token: ${{ secrets.GH_PAT }}
        path: other-repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run python script
      run: |
        cd other-repo
        python scipt.py 
      
